### ISSUE TITLE
rework autoloader

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/order#103]
see glpi-project/glpi#1855

we need to include (or drop) Zend\Loader\SplAutoloader

**Comment by trasher** [comment]
As far as I can see; the autoloader is used for the odtphp library.

The way to go would be to use composer to retrieve it; and drop both autoloader stuff and lib directory but... The local copy has been modified; and this was not reported upstream apparently.

We should propose a PR upstream to port the fix, and then use composer in the plugin.

**Comment by trasher** [comment]
Fixed in develop
