### ISSUE TITLE
Why update inventory number

### ISSUE THREAD

**Issue by alex8276** [pluginsGLPI/order#105]
Hello,
I trying this plugin. When I receive an order, that create my computer object, ok. By default a inventory number is create by me.
After, I put the series number and that delete my inventory number. Why ? And how to remove that. I need to conserve my inventory number.
Regards

PS: SOrry to my english

**Comment by cedric-anne** [comment]
Hi,

I did not reproduce this issue using GLPI 9.3 + Order 2.1.1.
Which versions of GLPI and Order plugin do you use ? If you reproduce this issue, can you give more details about the scenario to reproduce it.

Regards

**Comment by cedric-anne** [comment]
Hi,

Without feedback, I cannot investigate. I close this issue. Feel free to reopen.

Regards
