### ISSUE TITLE
How updating Order plugins without loose report or data ?

### ISSUE THREAD

**Issue by tech62** [pluginsGLPI/order#107]
How updating Order plugins without loose report or data ?

Thx !

**Comment by trasher** [comment]
You should  only install the new version. Did you have issues?

**Comment by tech62** [comment]
i don't have issue with the previous version, but i've never updated this plugins before (actually version 1.9.5).

I've modify templates for the odt generation and don't want to loose my work ;)

**Comment by trasher** [comment]
I don't know where you stored your odt file; but if you backup your actual plugin directory; you should not loose anything.

**Comment by tech62** [comment]
The ODT templates are stored in glpi/plugins/order/templates/.
I've downloaded the zip of the repository and decompress in the plugins folder, the plugins list isn't display.

Any solution to fix that ?

**Comment by trasher** [comment]
Make sure the directory is name "order", and the old one is not in the plugins directory

**Comment by tech62** [comment]
i've renamed the older like "orderbak" and restored when i see the bug, but same bug

**Comment by trasher** [comment]
check the directory rights

**Comment by tech62** [comment]
I've perform a chown -R www-data:www-data order, and check right, but that's not work  :/

**Comment by tech62** [comment]
In debug mode glpi told :

> PHP Warning: include_once(/var/www/glpi/plugins/order/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/glpi/plugins/order/setup.php at line 65
PHP Warning: include_once(): Failed opening '/var/www/glpi/plugins/order/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/glpi/plugins/order/setup.php at line 65

**Comment by tech62** [comment]
It's ok, i've forgot to move the folder orderbak out of the folder "plugins"
`
 Fatal error: Cannot redeclare plugin_init_order() (previously declared in /var/www/glpi/plugins/order/setup.php:74) in /var/www/glpi/plugins/orderbak/setup.php on line 67`

**Comment by trasher** [comment]
I'm lost... Is that working or not?

**Comment by tech62** [comment]
The plugins list working, i've do the update.
The last error who persist : 

`PHP Warning: include_once(/var/www/glpi/plugins/order/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/glpi/plugins/order/setup.php at line 65 PHP Warning: include_once(): Failed opening '/var/www/glpi/plugins/order/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/glpi/plugins/order/setup.php at line 65`

And effectively there is no vendor folder in the repository or in the zip generated or in the previous folder version of the plugins.

**Comment by trasher** [comment]
So you took the plugin sources and not the release.... You have to download glpi-order-1.9.6.tar.bz2
