### ISSUE TITLE
PHP error in dbmysql.class.php with order plugin activated

### ISSUE THREAD

**Issue by dwalraet** [pluginsGLPI/order#109]
Edit a supplier is not possible in glpi 9.1.2 and in apache error log I see this error :

PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc() on boolean in dbmysql.class.php:308\nStack trace:\n#0 db.function.php(320): DBmysql->fetch_assoc(false)\n#1 commondbtm.class.php(1876): countElementsInTable('glpi_plugin_dom...', '`glpi_suppliers...')\n#2 commondbtm.class.php(2372): CommonDBTM->canUnrecurs()\n#3supplier.class.php(133): CommonDBTM->showFormHeader(Array)\n#4 commonglpi.class.php(473): Supplier->showForm('6', Array)\n#5 ajax/common.tabs.php(97): CommonGLPI::displayStandardTab(Object(Supplier), 'Supplier$main', '', Array)\n#6 {main}\n  thrown in dbmysql.class.php on line 308, referer: http://glpi/glpi/front/supplier.form.php?id=6
If I disabled order plugin and I create new supplier, I can edit this
Could you please help me

**Comment by dwalraet** [comment]
I have solved my problem with explanation in topic id=35099 found in glpi forum

best regards

dwalraet

**Comment by btry** [comment]
Hi
Is it the following post which helped you ?

http://forum.glpi-project.org/viewtopic.php?pid=173454#p173454

If yes, you should probably submit a pull request with the fix on the plugin domains.

Thank you

**Comment by dwalraet** [comment]
Hi,


Yes, this topic help me and after modification in hook.php file in domains plugin my problem is solved.

Thank you,


best regards


Didier

?
