### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by MikelH93** [pluginsGLPI/order#111]
Hello !

I have an error when i'm trying to install the plugin (version : 1.9.6) : 

update itemtype of table glpi_tickets for PluginOrderBudget - Erreur durant l'éxecution de la requête : UPDATE `glpi_tickets` SET `itemtype` = 'PluginOrderBudget' WHERE `itemtype` = '3153' - L'erreur est Unknown column 'itemtype' in 'where clause'

GLPI version : 9.1.2

There was an man that had the same error but i see that his ticket is closed because he had not answer to your questions.

Thanks to you

Sorry if my english is not perfect, i'm french.

**Comment by MikelH93** [comment]
To precise more, i'm trying to update the plugin from 1.1.1 version to his last.

**Comment by cedric-anne** [comment]
Hi,

It is related to a really old code in GLPI core that was made to migrate from 0.72 to 0.80 GLPI datamodel. I will try to investigate to found the best way to fix it.

Regards

**Comment by pewek1** [comment]
Hi, i have this same problem with GLPI version 9.4, and plugin version 2.4.0. I'm installing the plugin for the first time, not updating. Is there any posibility to fix it?

**Comment by cedric-anne** [comment]
Hi,

Sorry for the late.

Is https://github.com/glpi-project/glpi/pull/5544 fixing the issue ?

Regards

**Comment by cedric-anne** [comment]
Hi,

Will be fixed in GLPI 9.4.1 and above by https://github.com/glpi-project/glpi/pull/5544.

Regards
