### ISSUE TITLE
Management composants

### ISSUE THREAD

**Issue by alex8276** [pluginsGLPI/order#113]
Hello,
How to manage an order of HDD ? When I select an "other type" as elmeent's, when i revceive my order an element is create but where ? When I click on, the URL is  /plugins/order/front/other.form.php?id=1 but this page don't exist. 
So how to link my order with my hdd ?

Regards
and sorry to my English

**Comment by cedric-anne** [comment]
Hi,

It is not possible for now to handle devices like HDD in orders. List of items that are supported is hardcoded inside the plugin (see https://github.com/pluginsGLPI/order/blob/develop/setup.php#L97). You can patch this list to add `DeviceHardDrive` and you will be able to create supplier references for this type of items.

The `Other type` you choosed is in fact a custom type of the plugin that enable to put all references that are not linked to any GLPI core item type. The fact that an item is generated is a bug on automatic asset generation process. When using the manual generation process, it is disabled for this type of items.

Regards
