### ISSUE TITLE
Problems by generating "Purchase order" odt

### ISSUE THREAD

**Issue by timsieler** [pluginsGLPI/order#117]
I have a problem by generation the odt File for purchasing.

Nothing happen when i startet to generate a purchasing sheet. 

Can you give me a hint where to start searching the bug in my setting?

thanks a lot.

**Comment by cedric-anne** [comment]
Hi,

You could check PHP logs. If you provide us some PHP logs, it could help to figure out what is happening.

If your generation script is trying to fill a field that does not exists in your ODT file, it will fail. See https://github.com/pluginsGLPI/order/issues/172.

Regards

**Comment by cedric-anne** [comment]
Hi,

Without feedback, I cannot investigate. I close this issue. Feel free to reopen.

Regards
