### ISSUE TITLE
Add purchase request

### ISSUE THREAD

**Issue by amma35** [pluginsGLPI/order#120]
Adding a new purchase request feature:
- Adding rights management
A new right will be created for the management of purchasing requests. It will be possible to add the rights to create, read, update, delete and validate purchase requests.
![droit](https://cloud.githubusercontent.com/assets/15138371/26155204/b10d4b06-3b12-11e7-8029-dfa39c5b359d.png)

- Added in the menu
In the menu interface, "Purchase Requests" will be added. This menu will redirect to the list of purchase requests.
![menu](https://cloud.githubusercontent.com/assets/15138371/26155210/b56b19f8-3b12-11e7-8fed-a8e362c2ca27.png)

- Purchase Request Form
It will be possible to make a purchase request from a ticket or from the menu previously used.
![demandeachat_ticket](https://cloud.githubusercontent.com/assets/15138371/26155219/bf42efa0-3b12-11e7-9ac0-8c27b8c0d33e.png)

- Notifications 
- List of Purchase Requests
From the menu, a redirection to the list of different purchasing requests is visible. In this list, it will be possible to consult each purchase request.
Massive action will be added to allow binding to an order already created.
- Purchase request in orders
In each order, a new "Purchase Request" tab will be present. In this tab, the purchase requests that have been linked will be visible in list form.
It will be possible to delete the binding of the purchase request of the order through the massive action.
![listeda_order](https://cloud.githubusercontent.com/assets/15138371/26155249/d81ca084-3b12-11e7-9e49-f374186775a3.png)

I send a pull request as soon as possible.

**Comment by wawax** [comment]
Hi @amma35 

That sounds interesting.
I would be interested in discussing not adding a purchase request but adding a ticket. This way, we could add forms to formcreator to create a ticket.

So form using formcreator => ticket using a template => validation => order
or
form using formcreator => form validation => ticket => order (so linking order creation to a ticket validation)
or
form using formcreator => form validation => order (so adding an order target to formcreator)

What do you think about that ? (I'm trying to avoid having another validation workflow as we have one in formcreator and in glpi itself)

**Comment by wawax** [comment]
@btry what do you think also about that ?

**Comment by btry** [comment]
Hi

While reading I thought immediately about creating a new target "Order".

Why create a ticket when requesting to buy hardware ? Tickets are for issues or incidents. If an issue or an incident may be solved by buying hardware, we may link the ticket and the order. 

Moreover, if the workflow states a ticket must be created when a order request is created, a form in FormCreator may be defined with two targets: a ticket and an order.

If we use FormCreator to generate orders, I think it will be tricky to allow a random quantity of objects with random type (depending on how the form designer wants to allow).

We need to define various use cases to know the complexity of the development in FormCreator. Maybe we should first target real use cases @amma35 has to solve: I already guess we will have challenging use case for FormCreator's user interface (both for administrator and requester).

**Comment by tsmr** [comment]
In our process : 

1. A user create a ticket (Request) for request a material.
2. The ticket is validated.
3. The person in charge of purchase create a purchase request which be validated too
4. The purchase request is validated
5. The person of charge of orders create an order from multiple purchase requests

So it was complicated to use formcreator with this process, because request ticket is the source and we need notifications for this process too.

**Comment by btry** [comment]
With this use case, the last scenario @wawax submitted does not match. Others may match.

**Comment by wawax** [comment]
Thanks @tsmr , I now understand the workflow.
I'd be in favour of an automation to create the order automatically. I see 2 possibilities : 
- link to a ticket template the automatic generation of an order template. So when an ticket for a purchase order is validated a new order is created using the template
or 
- a manual form to be display when the ticket is validated but no order is created to manually create a new one

What do you think about that @amma35 @tsmr ?

**Comment by tsmr** [comment]
The purchase request is essential in our process (Cumulative validations). 

So, we will develop a dedicated plugin if actually our process is not compatible with the orientation of the plugin

**Comment by wawax** [comment]
I think we missunderstood each other @tsmr.
I'm not saying that I'm against purchase request, but I'm saying that we can link tickets to purchase request either automatically or manually from the ticket view (by example having appearing when the ticket is linked to a specific category).

So ticket => ticket's validation => pucharse request => purchase request validation => order

By the way it would be the right time to start working on unit tests, as the plugin's code is a mess ^^

**Comment by amma35** [comment]
So if I understand correctly, we can include purchasing requests in the "Order" plugin?

On the other hand, we only took into account the manual creation of purchasing requests.

The development is almost done I can propose a PR?

**Comment by wawax** [comment]
I'd be interested in reviewing this PR yes
