### ISSUE TITLE
Supplier Notification - Order info

### ISSUE THREAD

**Issue by haidep** [pluginsGLPI/order#125]
Is there any option to send a email (Notification) to the Supplier when Order is validated with the Order Info ?
I think that i will be the correct way to send the Order to the Supplier automacatly, isn´t it?

**Comment by haidep** [comment]
please... i need help with this point.
When i do the order i fill wiht supplier info ( Supplier and Contact fields) but nothing happens... Supplier doesn't received email with Items added to order.
Maybe there is some rule to configure or some automatic action that i don't kwown..
Is there some guide about the plugin that explain notifications that send?

**Comment by haidep** [comment]
really  can nobody tell me nothing about this?
Come on please i need some help, i don't find any info about this

**Comment by cedric-anne** [comment]
Hi,

Done in commit 9a6d06ff9af259f72868f495a1a35873d8a2880b.

Regards
