### ISSUE TITLE
Calculation Issue with Discount

### ISSUE THREAD

**Issue by ukef** [pluginsGLPI/order#13]
There is an error in calculation with Discount / see attachment

Plugin Version 0.85+1.0

Thanks
![order-management-issue](https://cloud.githubusercontent.com/assets/15626966/10961191/7daa48d4-838c-11e5-8723-9a0852382a58.jpg)

**Comment by tsmr** [comment]
Already corrected https://github.com/pluginsGLPI/order/pull/10
