### ISSUE TITLE
Purchase order generator failed with custom odt file

### ISSUE THREAD

**Issue by rubbermaid123** [pluginsGLPI/order#130]
When i try to generate purchase order with a custom odt file with the same fields that the original odt file, it's failed and display error 500.

Attached, the custom odt file.
[commande-ccsc.zip](https://github.com/pluginsGLPI/order/files/1122231/commande-ccsc.zip)

**Comment by trasher** [comment]
Hello,

Could you provide errors logged in log files when the error occurs? Thanks.

**Comment by rubbermaid123** [comment]
Tue Jul 04 09:23:30.727773 2017] [:error] [pid 15201] [client 10.95.80.202:62273] PHP Fatal error:  Uncaught Error: Class 'Odtphp\\SegmentException' not found in /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php:156\nStack trace:\n#0 [internal function]: Odtphp\\Segment->setVars('refArticle', 'SHS1890-15')\n#1 /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php(227): call_user_func_array(Array, Array)\n#2 /var/www/html/glpi/plugins/order/inc/order.class.php(1573): Odtphp\\Segment->__call('refArticle', Array)\n#3 /var/www/html/glpi/plugins/order/front/export.php(33): PluginOrderOrder->generateOrder(Array)\n#4 {main}\n  thrown in /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php on line 156, referer: http://inventaire.intranet.ccscapitales.com/plugins/order/front/order.form.php?id=1
[Tue Jul 04 09:23:59.558828 2017] [:error] [pid 15153] [client 10.95.80.202:62284] PHP Fatal error:  Uncaught Error: Class 'Odtphp\\SegmentException' not found in /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php:156\nStack trace:\n#0 [internal function]: Odtphp\\Segment->setVars('refArticle', 'SHS1890-15')\n#1 /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php(227): call_user_func_array(Array, Array)\n#2 /var/www/html/glpi/plugins/order/inc/order.class.php(1573): Odtphp\\Segment->__call('refArticle', Array)\n#3 /var/www/html/glpi/plugins/order/front/export.php(33): PluginOrderOrder->generateOrder(Array)\n#4 {main}\n  thrown in /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php on line 156, referer: http://inventaire.intranet.ccscapitales.com/plugins/order/front/order.form.php?id=1
[Tue Jul 04 09:24:03.263692 2017] [:error] [pid 15120] [client 10.95.80.202:62285] PHP Fatal error:  Uncaught Error: Class 'Odtphp\\SegmentException' not found in /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php:156\nStack trace:\n#0 [internal function]: Odtphp\\Segment->setVars('refArticle', 'SHS1890-15')\n#1 /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php(227): call_user_func_array(Array, Array)\n#2 /var/www/html/glpi/plugins/order/inc/order.class.php(1573): Odtphp\\Segment->__call('refArticle', Array)\n#3 /var/www/html/glpi/plugins/order/front/export.php(33): PluginOrderOrder->generateOrder(Array)\n#4 {main}\n  thrown in /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php on line 156
[Tue Jul 04 09:25:20.135953 2017] [:error] [pid 15201] [client 10.95.80.202:62322] PHP Fatal error:  Uncaught Error: Class 'Odtphp\\SegmentException' not found in /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php:156\nStack trace:\n#0 [internal function]: Odtphp\\Segment->setVars('refArticle', 'SHS1890-15')\n#1 /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php(227): call_user_func_array(Array, Array)\n#2 /var/www/html/glpi/plugins/order/inc/order.class.php(1573): Odtphp\\Segment->__call('refArticle', Array)\n#3 /var/www/html/glpi/plugins/order/front/export.php(33): PluginOrderOrder->generateOrder(Array)\n#4 {main}\n  thrown in /var/www/html/glpi/plugins/order/vendor/masnathan/odtphp/src/Segment.php on line 156, referer: http://inventaire.intranet.ccscapitales.com/plugins/order/front/order.form.php?id=1
[

**Comment by rubbermaid123** [comment]
These errors was in apache2 error logs.
In GLPI logs, no error :S

**Comment by trasher** [comment]
Fatal errors cannot be catched; it's OK. Thanks for the log, it will probably help to understand what went wrong.

**Comment by BagorX** [comment]
After taking a look into your odt file I think I had the same problem. It took me 2 days of debugging the code and the odt files. In my case I hat to create in the folder "glpi/files/_plugins/order/generate" a custom.php. The problem seemed to be that an exception is thrown when the code tries to create an article related field with setVars that is not used in the odt file. So I modified my custom.php in the way that only those fields are created that my odt file needs. Then everything worked.

**Comment by cedric-anne** [comment]
Hi,

As explained by @BagorX, the root cause of this trace is taht your generation script tries to set a var called `refArticle` that does not exists in the `articles` segment. In the sample file, corresponding code is `$article->refArticle($element['refnumber']);`. If you remove the `{refArticle}` from the ODT file, you have to remove this code too.

Regards.
