### ISSUE TITLE
Massive action 

### ISSUE THREAD

**Issue by stonebuzz** [pluginsGLPI/order#131]
In the previous version it was possible to modify in bulk the fields of the plugin, but this is no longer possible

![image](https://user-images.githubusercontent.com/7335054/28054830-ca59a3e6-6616-11e7-8565-6e863dacc75d.png)

Plugin version  -> 1.9.5

**Comment by cedric-anne** [comment]
Hi,

I do not know why, but update action is forbidden since, at least, 0.85.
https://github.com/pluginsGLPI/order/blob/0.85%2B1.0/inc/order.class.php#L1957

Regards
