### ISSUE TITLE
No existing peripherals in the order

### ISSUE THREAD

**Issue by mdesmaris** [pluginsGLPI/order#132]
Hi
sorry for my bad english

I have in my glpi 200 computers, 200 screens, 100 peripherals.
I wish to integrate all informations of these materials with all orders since 2016.
But when I create a order, I can't add a péripheral which already exists
the list in "Elements de la commande" in french or in english may be "Order Elements", this list is empty.

It's a real problem that it's impossible to link my existing datas with an order.

Thank you for your help.

Manu

**Comment by mdesmaris** [comment]
Hello,
Up
an idea?
Pleasseeeeeeee!!
:'(

**Comment by cedric-anne** [comment]
Hi,

To be able to add items into an order, you must add them into the product reference list (menu `Management` > `Order` > `Products references` or URL `plugins/order/front/reference.php`). Also, the `Supplier` of items must match the `Supplier` of the order. Doing this will give you the ability to create orders that contains your product reference.

Now, to link orders with existing, computers, screens and peripheral, you have to:
- create an order,
- add items to the order in the `Order items` tab,
- validate the order in the `Validation` tab,
- mark items as delivered in the `Items delivered` tab using mass action `Take item delivery`,
- link the order item to your asset in the `Associated items` tab using mass action `Link to an existing item`.
