### ISSUE TITLE
How to use Signatures

### ISSUE THREAD

**Issue by cchable** [pluginsGLPI/order#134]
I created a signatures folder (order / signatures). I put a png image in it but it is not available in dropdown.

**Comment by BagorX** [comment]
The folders seem to have changed with one the last updates. I had to work it out for my installation and found in the code that it points to "glpi/files/_plugins/order/signatures". You have also to put there the folders "templates" for the odt-templates and "generate" for the "custom.php".

**Comment by cedric-anne** [comment]
Hi,

After a quick search in the code, I found that to be usable by a user, a signature must follow this pattern: `{$username}.*.png`. So a signature cannot be shared between users.

I searched in file history to find why and I figure it has been done like that from the beginning.

Regards.

**Comment by cedric-anne** [comment]
Hi,

There is a bug with preference form. When you choose a signature, it is not well displayed as it tries to load it from the old path. Problem is that the new path is protected by default from beeing accessed using web server.

It should be fixed.

Regards

**Comment by zzroot29** [comment]
Yes,
I put the 'username'.png file in this folder ( "glpi/files/_plugins/order/signatures".). I can select it in combo list in user's preference.
When i go to the purchase order generation page, the signature is ok and selected in the combo, but if generate the purchase : 

PHP Warning: getimagesize(../signatures/stephane.png): failed to open stream: No such file or directory in /var/www/glpi/plugins/order/vendor/masnathan/odtphp/src/Odf.php at line 134

Fatal error: Uncaught Odtphp\Exceptions\OdfException: Invalid image in /var/www/glpi/plugins/order/vendor/masnathan/odtphp/src/Odf.php:136 Stack trace: #0 /var/www/glpi/files/_plugins/order/generate/custom.php(185): Odtphp\Odf->setImage('sign', '../signatures/s...') #1 /var/www/glpi/plugins/order/inc/order.class.php(1592): plugin_order_getCustomFieldsForODT('49', 'uniha.odt', Object(Odtphp\Odf), 'stephane.png') #2 /var/www/glpi/plugins/order/front/export.php(33): PluginOrderOrder->generateOrder(Array) #3 {main} thrown in /var/www/glpi/plugins/order/vendor/masnathan/odtphp/src/Odf.php on line 136

**Comment by cedric-anne** [comment]
@zzroot29 

The generation script sample was not up to date. Commit https://github.com/pluginsGLPI/order/pull/182/commits/491108a5420fc497e349ad65fabcfac1563157ac should fix your problem.

Regards

**Comment by zzroot29** [comment]
Cédric-Anne : TOP ! Nickel (in english please !) everything works perfectly.
Thank's a lot.
