### ISSUE TITLE
My settings > Orders > empty dropdown lists

### ISSUE THREAD

**Issue by vahraba** [pluginsGLPI/order#135]
Model and sign dropdown lists are empty. However the file "example.odt" is present in the directory glpi/plugins/order/templates but it is not displayed in the dropdown list.

**Comment by tech62** [comment]
See https://github.com/pluginsGLPI/order/pull/133
You could put your files in glpi/_files/plugins/order/templates and glpi/_files/order/generate for your custom.php
Make the folder if they're not present.

**Comment by vahraba** [comment]
Thanks for your support.
The file "example.odt" was already in "/glpi/plugins/order/templates" and the file "custom.php" in "/glpi/plugins/order/generate".
Are there any configurations to do?
I use a clean installation of GLPI 9.1.6 from remi's RPM with PHP 5.6.32.

**Comment by tech62** [comment]
Your file will be in glpi/**files**/_plugins/order/templates/example.odt and glpi/**files**/_plugins/order/generate/custom.php not in glpi/plugins/order/templates and glpi/plugins/order/generate ;)

**Comment by vahraba** [comment]
Thanks, now I can select odt files in the dropdown list (My settings >Orders) ;).
But Order generation give me error 500.

Below ssl_error_log from httpd :
[Tue Oct 31 13:37:45.548564 2017] [:error] [pid 1461] [client XX.XX.XX.XX:XXXXX] PHP Fatal error: Uncaught exception 'Odtphp\\Exceptions\\OdfException' with message 'var comment not found in the document' in /usr/share/glpi/plugins/order/vendor/masnathan/odtphp/src/Odf.php:109\nStack trace:\n#0 /var/lib/glpi/files/_plugins/order/generate/custom.php(44): Odtphp\\Odf->setVars('comment', '', true, 'UTF-8')\n#1 /usr/share/glpi/plugins/order/inc/order.class.php(1461): plugin_order_getCustomFieldsForODT('30', 'example.odt', Object(Odtphp\\Odf), '0')\n#2 /usr/share/glpi/plugins/order/front/export.php(33): PluginOrderOrder->generateOrder(Array)\n#3 {main}\n  thrown in /usr/share/glpi/plugins/order/vendor/masnathan/odtphp/src/Odf.php on line 109, referer: https://XXXXX.XXXXXX.com/glpi/plugins/order/front/order.form.php?id=30.

Any idea ?

**Comment by tech62** [comment]
Try to comment the line `Odf->setVars('comment', '', true, 'UTF-8')` in your custom.php.
Have you added the comment field by yourself in the custom.php ?

**Comment by vahraba** [comment]
Thanks for your premium support ;)
I also comment the line  `Odf->setVars('entity_ldapdn', NULL, true, 'UTF-8')` in my custom.php and it works ;)
I did not modify my odt file (I use the original example.odt)
Do you know if It's possible to generate pdf instead of odt files ?

**Comment by tech62** [comment]
Directly in pdf , i don't know , it could be requested as a new feature ^^
But i generate odt file and in openoffice / libreoffice / MSOffice, i export it in pdf ;)

**Comment by tech62** [comment]
Install openoffice or libreoffice and :
Comment the line 1686 in /glpi/plugins/order/inc/order.class.php
`//$odf->exportAsAttachedFile($outputfile);`
And add this
` 
    $odf->saveToDisk('/tmp/' . $outputfile);
        $pdffile = preg_replace('"\.odt$"', '.pdf', $outputfile);
        $command="export HOME=/tmp; soffice --headless --invisible --norestore  --convert-to pdf:writer_pdf_Export /tmp/$outputf$
        $res=shell_exec($command);
        echo '<a href="../../../' . $pdffile . '">Download</a>';
`
I'm not a developer, so the code is certainly bad, but it's functionnal !

**Comment by vahraba** [comment]
Thanks you very much ;) 
I will try your solution later.

**Comment by tech62** [comment]
To manage the pdf file, there's a possibility to use the API, or searching the functions in the code who's moving and indexing the file in the database.

**Comment by tech62** [comment]
Do you know how to convert this  :
`$data = array("uploadManifest" => array ("input" => array(
                                                                "name" => "Uploaded document",
                                                                "_filename" => "[file.txt]"
                                                                )
                                        )
                );`

In object ?

**Comment by vahraba** [comment]
No, I don't know sorry :/

**Comment by cedric-anne** [comment]
Hi,

As root problem was solved, I close this issue.

Regards

**Comment by marcosluv** [comment]
hello i have one problem before change my archive order.class.php 

Parse error: syntax error, unexpected 'Cache' (T_STRING) in /var/www/html/glpi/plugins/order/inc/order.class.php on line 1849

please help me
