### ISSUE TITLE
Error in php-error.log

### ISSUE THREAD

**Issue by mrspam** [pluginsGLPI/order#136]
Hi !

I have this error in my php error log file.
GLPI version 9.2.1 same error with 9.2 version thanks for your help.

2017-11-17 12:37:23 [430@xxx]
  Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/notificationtarget.class.php:135               Toolbox::deprecated()
  inc/notificationtarget.class.php:291               NotificationTarget->__construct()
  inc/notificationtarget.class.php:310               NotificationTarget::getInstance()
  inc/notificationevent.class.php:92                 NotificationTarget::getInstanceByType()
  inc/notification.class.php:269                     NotificationEvent::getEventName()
  inc/search.class.php:5039                          Notification::getSpecificValueToDisplay()
  inc/search.class.php:1147                          Search::giveItem()
  inc/search.class.php:98                            Search::constructDatas()
  inc/search.class.php:81                            Search::showList()
  front/notification.php:44                          Search::show()
2017-11-17 12:37:23 [430@xxx]
  From Toolbox::deprecated() in /var/www/glpi/inc/toolbox.class.php line 477 (0.039", 4.73Mio)
  getAdditionalTargets() method is deprecated (PluginOrderNotificationTargetOrder)
2017-11-17 12:37:23 [430@xxx]
  Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/notificationtarget.class.php:135               Toolbox::deprecated()
  inc/notificationtarget.class.php:291               NotificationTarget->__construct()
  inc/notificationtarget.class.php:310               NotificationTarget::getInstance()
  inc/notificationevent.class.php:92                 NotificationTarget::getInstanceByType()
  inc/notification.class.php:269                     NotificationEvent::getEventName()
  inc/search.class.php:5039                          Notification::getSpecificValueToDisplay()
  inc/search.class.php:1147                          Search::giveItem()
  inc/search.class.php:98                            Search::constructDatas()
  inc/search.class.php:81                            Search::showList()
  front/notification.php:44                          Search::show()
2017-11-17 12:48:01 [@xxx]
  From Toolbox::deprecated() in /var/www/glpi/inc/toolbox.class.php line 477
  TableExists() function is deprecated
2017-11-17 12:48:01 [@xxx]
  Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/order/inc/config.class.php:43              TableExists()
  plugins/order/inc/config.class.php:60              PluginOrderConfig->__construct()
  plugins/order/inc/order.class.php:1922             PluginOrderConfig::getConfig()
  inc/crontask.class.php:832                         PluginOrderOrder::cronComputeLateOrders()
  front/cron.php:87                                  CronTask::launch()
2017-11-17 13:48:01 [@xxx]
  From Toolbox::deprecated() in /var/www/glpi/inc/toolbox.class.php line 477
  TableExists() function is deprecated
2017-11-17 13:48:01 [@xxx]
  Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/order/inc/config.class.php:43              TableExists()
  plugins/order/inc/config.class.php:60              PluginOrderConfig->__construct()
  plugins/order/inc/order.class.php:1922             PluginOrderConfig::getConfig()
  inc/crontask.class.php:832                         PluginOrderOrder::cronComputeLateOrders()
  front/cron.php:87                                  CronTask::launch()

**Comment by trasher** [comment]
Tis plugin is not yet compatible with GLPI 9.2.
