### ISSUE TITLE
documentcategory.php  is missing

### ISSUE THREAD

**Issue by Cit35** [pluginsGLPI/order#138]
Hi all, 

in setup/orders management/Orders
the file glpi/plugins/order/front/documentcategory.php  is missing

where can I find it ?

thnx

**Comment by cedric-anne** [comment]
Hi,

I cannot find any link to this file. Where did you find it ?

Regards

**Comment by cedric-anne** [comment]
Hi,

Without feedback, I cannot investigate. I close this issue. Feel free to reopen.

Regards
