### ISSUE TITLE
issue when Ask for validation 

### ISSUE THREAD

**Issue by Cit35** [pluginsGLPI/order#139]
Hi all,
On Orders/Order/Validation tab
click on "Ask for validation", nothing appends
in debug mode, I can see a PHP Notice in red
PHP Notice: Undefined index: notificationtemplates_id in /var/www/glpi/inc/notificationevent.class.php at line 136

In Notification template, I have default template

Order Delivered
Order Validation

in default language

What I have to check more ?

Thnx

GLPI 9.1.6 / Orders plugin 1.9.7

**Comment by cedric-anne** [comment]
Hi,

It seems that your notifications are not installed correctly.

In `Setup` > `Notifications` > `Notifications`, you should have a notification named `New Order Validation`.
If it exists, just check these values are correctly defined as described below.
If it does not exist, you have to create it using the template `Order Validation` using following values:
 - name: `New Order Validation` or whatever you want,
 - type: `Order`,
 - event: `Request order validation`.
In the `Recipients` tab, define who should receive the notification.
In the `Template` tab of the notification, click on `Add a template` button, choose `Email` mode and `Order Validation` template, then click on `Add` button.
