### ISSUE TITLE
Problems with a the price of the Discount product > 1000€ 

### ISSUE THREAD

**Issue by bielgv09** [pluginsGLPI/order#14]
Hi,
We have a display problem with the plugin Order management.
For example, the taxe free price is not equivalent with the real price. 
Can you help me ?
Here is a Screenshot for illustrate my issue: 
![glpi_bug1](https://cloud.githubusercontent.com/assets/15672151/10970946/ef941bf6-83d1-11e5-8ba3-9d79c7b677c3.png)
![glpi_bug2](https://cloud.githubusercontent.com/assets/15672151/10970956/f82dce2e-83d1-11e5-8d34-bc7ab2e04fe4.jpg)
![bug_glpi](https://cloud.githubusercontent.com/assets/15672151/10970961/ff154c80-83d1-11e5-82a8-f3b42eba1c9b.jpg)

**Comment by tsmr** [comment]
Already corrected https://github.com/pluginsGLPI/order/pull/10
