### ISSUE TITLE
Associate helpdesk ticket with order

### ISSUE THREAD

**Issue by Arcacat** [pluginsGLPI/order#140]
Hello, 

I use GLPI platform on a regular basis. I noticed that when I create an order, there is a drop down menu after the question: Associable to ticket: Yes/No.
However, after click yes and saving it, I do not see how it is possible to associate it with a helpdesk ticket. It can be associated with assets (computers, devices, and such) but no tickets can be associated. 

Is there anyway, a plug in perhaps that can be made to make orders and helpdesk tickets associable to each other? 

Thanking you all in advance for a quick reply.

Best,
Arcacat

**Comment by cedric-anne** [comment]
Hi,

To be able to associate an order to a ticket, you must satify following requirements:
- The `Associable to a ticket :` must be set to `yes` in the order.
- The `Order` item type must be added to the `Associable items to a ticket` for the profile used by user. This can be defined in the `Association` section of `Assistance` tab inside the profile administration page.
- The profile used by user must have rights to link orders to a ticket. This can be defined in the `Orders` tab inside the profile administration page.

Point 3 seems redundent with point 2 but is mandatory. I need to check why it has been made like this and if it is really needed.
