### ISSUE TITLE
Problème génération bon de commande

### ISSUE THREAD

**Issue by GuillaumeBru** [pluginsGLPI/order#151]
Bonjour, 

J'ai un problème lors de la génération d'un bon de commande, j'ai une erreur 500.

**Versions :** 
- GLPI : 9.2.1
- Order : 2.0.0

**Fichier : files/_log/php-errors.log**
_2018-02-19 09:25:16 [7@MONTPELLIER]
  *** PHP Warning(2): include_once(/var/www/glpi/plugins/order/vendor/autoload.php): failed to open stream: No such file or directory
  Backtrace :
  plugins/order/setup.php:67
  plugins/order/setup.php:67                         include_once()
  inc/plugin.class.php:140                           include_once()
  inc/includes.php:118                               Plugin::load()
  plugins/order/front/export.php:30                  include()
2018-02-19 09:25:16 [7@MONTPELLIER]
  *** PHP Warning(2): include_once(): Failed opening '/var/www/glpi/plugins/order/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear')
  Backtrace :
  plugins/order/setup.php:67
  plugins/order/setup.php:67                         include_once()
  inc/plugin.class.php:140                           include_once()
  inc/includes.php:118                               Plugin::load()
  plugins/order/front/export.php:30                  include()_

**Fichier : files/_log/sql-errors.log**
_vide_

Vu l'erreur présente dans les logs, le plugin cherche un fichier plugins/order/vendor/autoload.php mais dans le plugin il n'y a pas de fichier autoloard.php et de dossier vendor.

Pouvez-vous m'aider ?

Merci !

**Comment by trasher** [comment]
The release archive do provide the vendor directory.

See https://github.com/pluginsGLPI/order/releases/tag/2.0.0 and make sure to get the release, not one of the "source code".
