### ISSUE TITLE
New Purchase order pb with version 2.1 on GLPI 9.3

### ISSUE THREAD

**Issue by zzroot29** [pluginsGLPI/order#172]
Hi all,

Another time : thank's to the team, your plugin saves us a huge amount of time every day! Our budget and our expenses are consolidated automatically thanks to you !

My pb : I Installed the last version of GLPI and update my ORDER plugin in same time.
I installed the compiled version of ORDER.

When i want to create a purchase in an order, i have this message in debug mode : 
Fatal error: Uncaught Odtphp\Exceptions\OdfException: var comment not found in the document in /var/www/glpi/plugins/order/vendor/masnathan/odtphp/src/Odf.php:109 Stack trace: #0 /var/www/glpi/files/_plugins/order/generate/custom.php(44): Odtphp\Odf->setVars('comment', '', true, 'UTF-8') #1 /var/www/glpi/plugins/order/inc/order.class.php(1592): plugin_order_getCustomFieldsForODT('49', 'uniha.odt', Object(Odtphp\Odf), '0') #2 /var/www/glpi/plugins/order/front/export.php(33): PluginOrderOrder->generateOrder(Array) #3 {main} thrown in /var/www/glpi/plugins/order/vendor/masnathan/odtphp/src/Odf.php on line 109

SB.

**Comment by cedric-anne** [comment]
Hi,

Provided example tries to fill field that does not exists in `example.odt` file.
Foillowing patch should fix your problem: https://github.com/pluginsGLPI/order/pull/174/files.

Regards

**Comment by zzroot29** [comment]
Thank's a lot -> You solve my pb.
I had the same message with the lign 65, then i comment it and it works like a charm.

At this time i'm looking for the signature file to join with the odt file. I understand that i can select this file in the Preferences of the user, but i don't find the place to umpload it (glpi/files/_plugin/order/signatures ??) But if i put an image jpg file in this folder, with the name test_sign.jpg, the combobox are not populate.
Can you give me somes informations aboiut signature in order ?

Many thanks for your help.

**Comment by cedric-anne** [comment]
Hi,

For the signature issue, I just added a comment on another issue that should help you https://github.com/pluginsGLPI/order/issues/134#issuecomment-407085950 .

Regards

**Comment by zzroot29** [comment]
Thank's a lot, i look this new issue.

Regards.
