### ISSUE TITLE
Survey Tab "quality supplier" in error

### ISSUE THREAD

**Issue by aldevar** [pluginsGLPI/order#173]
Hi, 

OS : Unbuntu 18.04
Web Server : Apache
PHP : 7.2
GLPI : 9.3
Order Management : 2.1.1

I've just upgraded from an old version of order plugin (1.X) to latest version.
I'va also upgraded to last version of glpi (9.3).
After closing a command, when I go to the tab 'quality supplier' (Qualité Fournisseur in french), an error message appears on the webpage : 
'Check you glpi logs or contact your administrator'.
In the apache2 logs, I can find this error : 
`[php7:error] [pid 37779] [client My.IP.AD.DR:49501] PHP Fatal error:  Uncaught Error: Cannot pass parameter 3 by reference in /var/www/glpi93/plugins/order/inc/surveysupplier.class.php:281\nStack trace:\n#0 /var/www/glpi93/plugins/order/inc/surveysupplier.class.php(524): PluginOrderSurveySupplier->showForm('', Array)\n#1 /var/www/glpi93/inc/commonglpi.class.php(478): PluginOrderSurveySupplier::displayTabContentForItem(Object(PluginOrderOrder), '1', '')\n#2 /var/www/glpi93/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginOrderOrder), 'PluginOrderSurv...', '', Array)\n#3 {main}\n  thrown in /var/www/glpi93/plugins/order/inc/surveysupplier.class.php on line 281, referer: https://glpi.sib.fr/plugins/order/front/order.form.php?id=2694`

How can I get back this feature?

Regards

**Comment by cedric-anne** [comment]
Hi,

Commit f7762b5fc388c34e32e6359a04489d0708d319bc should fix your problem.

Regards

**Comment by aldevar** [comment]
I confirm this patch fixes the issue.
Thank you!
