### ISSUE TITLE
Asset name harmonization

### ISSUE THREAD

**Issue by OscarBeiro** [pluginsGLPI/order#193]
Assets field in different screens shows different id names. 
In Order Item is named **Equipment** and in Item delivered, associated items and bill **Type**
![order_item](https://user-images.githubusercontent.com/18396050/44651919-dec9ab00-a9ea-11e8-9cc6-39cb031679ae.png)

![item_delivered](https://user-images.githubusercontent.com/18396050/44651933-e8531300-a9ea-11e8-9567-9394bd7e9b37.png)
![associated_items](https://user-images.githubusercontent.com/18396050/44651937-eee18a80-a9ea-11e8-98a6-14172fc6f794.png)
![bill](https://user-images.githubusercontent.com/18396050/44651940-f143e480-a9ea-11e8-9199-deddd5aefeee.png)

We understand  the name **Equipment** has been used to avoid confusion with Assets type.

To avoid this inconsistency, we suggest changing all of them to Assets, their GLPI name. This would be much more intuitive in our opinion.

**Comment by cedric-anne** [comment]
Closed by #194.
