### ISSUE TITLE
Price calculation still not working correctly

### ISSUE THREAD

**Issue by xarumanx** [pluginsGLPI/order#20]
This is closely related to #9 and #13 but slightly different:

When the price on the product is entered with a "," as decimal seperator (when adding directly from the reference and changing nothing), everything behind the decimal seperator is ignored. If a manually enter the (same) price with a "." as decimal separator the correct price shows up in the order.

**Comment by xarumanx** [comment]
The order form also does funny things (ignores everything after the whitespace) when a whitespace is found in the item price (which is automatically formatted like this when a product is added)

**Comment by gandrea** [comment]
I had the same problem. It works ok now after changing number format in General Setup/Default values to '1234.56' (no space, no comma and dot as decimal separator).
