### ISSUE TITLE
Problem in massive action in "Item delivered" tab

### ISSUE THREAD

**Issue by Pieurre** [pluginsGLPI/order#205]
Hello,
When you pick one ore more item in the list and click on "Actions" every time you have: **No selected items** like this:

![image](https://user-images.githubusercontent.com/6872020/45741839-e13db000-bbf8-11e8-8933-953dbf20c158.png)

Thank you

**Comment by cedric-anne** [comment]
Hi,

I do not have this problem using GLPI 9.3.1 and Order 2.2.0.

Which versions do you use ?

Regards

**Comment by cedric-anne** [comment]
Hi,

It is related to `max_input_vars` limit of your PHP server. Even if you select only one item, the request made to the server contains, for each displayed element in the list, following variables:
- add_items[$id][id],
- add_items[$id][name],
- add_items[$id][plugin_order_references_id],
- add_items[$id][itemtype],
- add_items[$id][templates_id],
- add_items[$id][states_id],
- item[PluginOrderReception][$id]

200 * 7 = 1400 variables, which is more than the default 1000 limit (see http://php.net/manual/en/info.configuration.php).

Regards

**Comment by cedric-anne** [comment]
The best solution would be to fetch informations in massive action itself to not have to pass them. It requires a lot of work.

**Comment by cedric-anne** [comment]
Duplicates #69.
