### ISSUE TITLE
Bug process validation

### ISSUE THREAD

**Issue by JPRouanet** [pluginsGLPI/order#206]
Bonjour,
Lors du process de validation, le mail envoyé au valideur contient l'url de la commande à valider ( http://webserveur/glpi/index.php?redirect=plugin_order_order_309). Or ce lien n'est pas fonctionnel et reroute vers l'écran de gestion des plugins.

J'ai modifié le fichier order\inc\notificationtargetorder.class.php, ligne 71 et 141 pour avoir un url sans les underscore de part et d'autre de order. Cela donne ceci : ?redirect=pluginorderorder_".$this->obj->getField("id");
Cette modif est fonctionnelle. 

Pourriez-vous l'incorporer dans la prochaine update ?

Merci
Cordialement

**Comment by cedric-anne** [comment]
Bonjour,

Pourriez-vous tester la correction proposée ici : #207 ?

Cordialement
