### ISSUE TITLE
[IDEA] Buyer view

### ISSUE THREAD

**Issue by SylvainGuibert** [pluginsGLPI/order#215]
Hello,

We start to use Order plugin to manage our IT orders recently. (Thanks for that plugin!) In our organisation, we have technician that creates order and a buyer in charge of grouping orders and price optimization. All works well. 

During a week, orders are created. Orders are for some recipients but the supplier can be the same.
I would know if it is possible to create a synthetic view for the buyer, order buy supplier. The idea is to reduce administrative cost for our buyer. With this view, he does not have to open all commands and list all items. It can be easily for his to ask supplier. This view contains only items in order with the status "Waiting approval".

Perhaps we can image a view like this: 

Item Name, Quantity, Supplier, Order Number, Date of order, Author, Recipient

What do you think about this suggestion? If you need more information ask me, I will try to answer !

**Comment by OscarBeiro** [comment]
Hi,
I think you can achieve most of it out-of-the-box.

First:  you need a saved search with a filter:  Order-status - is - Waiting for validation. 
Second : On the wrench (beside the trashcan) a user with privileges can make his own view. Most of your needs could be addressed like this. adding supplier, date of order, author, etc.

![image](https://user-images.githubusercontent.com/18396050/48761890-0eb2e280-ecaa-11e8-9b1e-0bfe6c0b2f4d.png)

You might need a few more hours using the plugin :)

à bientôt 
Regards

**Comment by SylvainGuibert** [comment]
Thanks for your answer. 

I know i can set up personalized view, but, i cannot add the most important thing : items contains in order ! Does they have a way to do that ?

![2018-11-20_10h06_42](https://user-images.githubusercontent.com/16323410/48762767-06f43d80-ecac-11e8-91d1-003c0fc06212.png)

The idea is to have a view by items associated to an order and a supplier which are in pending state.

**Comment by OscarBeiro** [comment]
I see. Sorry I misunderstood.
They're not availabe right now.
You will need to develop this options, or ask teclib' or a partner to develop them for you.

**Comment by SylvainGuibert** [comment]
Perhaps it can be a new functionality of the next version of order. plugin.

**Comment by SylvainGuibert** [comment]
We made a combined view with an SQL query and a excel file ... 
If someone is interested, i can share the query. Ask me.
