### ISSUE TITLE
[Order 2.3.0] Error take item delivery

### ISSUE THREAD

**Issue by SylvainGuibert** [pluginsGLPI/order#224]
Hello,

I'am testing the 2.3.0 in our test environnement before upgrade on the production server. I have a issue with "take item delivery" action. When i do it on an order, i'am stuck on "massaction.php" page. If i come back to the delivery, only one item is passed as delivery. Others are waiting for delivery.

This is the backtrace : 

`PHP Notice: Undefined index: add_items in /var/www/glpidev/plugins/order/inc/link.class.php at line 1117

Fatal error: Uncaught Error: Class name must be a valid object or a string in /var/www/glpidev/plugins/order/inc/reference.class.php:418 Stack trace: #0 /var/www/glpidev/plugins/order/inc/link.class.php(1128): PluginOrderReference->checkIfTemplateExistsInEntity(168, NULL, '0') #1 /var/www/glpidev/plugins/order/inc/reception.class.php(934): PluginOrderLink->generateNewItem(Array) #2 /var/www/glpidev/plugins/order/inc/reception.class.php(808): PluginOrderReception::generateAsset(Array) #3 /var/www/glpidev/plugins/order/inc/reception.class.php(540): PluginOrderReception->updateReceptionStatus(Object(MassiveAction)) #4 /var/www/glpidev/inc/massiveaction.class.php(988): PluginOrderReception::processMassiveActionsForOneItemtype(Object(MassiveAction), Object(PluginOrderReception), Array) #5 /var/www/glpidev/inc/massiveaction.class.php(967): MassiveAction->processForSeveralItemtypes() #6 /var/www/glpidev/front/massiveaction.php(59): MassiveAction->process() #7 {main} thrown in /var/www/glpidev/plugins/order/inc/reference.class.php on line 418`

thanks for your help !

Sylvain

**Comment by stonebuzz** [comment]
Hi @SylvainGuibert can you test this PR ?

Bestregards
