### ISSUE TITLE
[GLPI 9.4.1.1] - [Order 2.4.0] : Product References Blank Page

### ISSUE THREAD

**Issue by SylvainGuibert** [pluginsGLPI/order#230]
Hi all,

Since we upgrade to GLPI 9.4.1.1 and Order Management 2.4.0, we have a "blank" page when we display the Product Reference page.  In latest version we can see directly all product references. 

No SQL Error. Trace on php-errors.log : 

[2019-04-02 10:45:08] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: itemtype
  Backtrace :
  plugins/order/hook.php:326
  inc/search.class.php:5266                          plugin_order_giveItem()
  inc/search.class.php:1441                          Search::giveItem()
  inc/search.class.php:98                            Search::constructData()
  inc/search.class.php:80                            Search::showList()
  plugins/order/front/reference.php:42               Search::show()
  {"user":"8@XXXXX"}
[2019-04-02 10:45:08] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: itemtype
  Backtrace :
  plugins/order/hook.php:313
  inc/search.class.php:5266                          plugin_order_giveItem()
  inc/search.class.php:1441                          Search::giveItem()
  inc/search.class.php:98                            Search::constructData()
  inc/search.class.php:80                            Search::showList()
  plugins/order/front/reference.php:42               Search::show()
  {"user":"8@XXXXX","mem_usage":"0.000\", 3.07Mio)"}

**Comment by albmol** [comment]
Hi all,

I have the same issue, when I go to product references all I get is a blank screen, I have activated the debug mode and I get the following error:
![References list error](https://user-images.githubusercontent.com/16403571/55491297-85d38c80-5635-11e9-8938-7a5e0e7a679c.png)
If I play with the filter, I can get a list of some references but I never get a full list

**Comment by cedric-anne** [comment]
Hi,

#232 should fix your issue.

Regards

**Comment by Cripix** [comment]
It's working

Thanks !
