### ISSUE TITLE
[GLPI 9.4.2] [Order 2.4.0] Page blanche dans Référence produit

### ISSUE THREAD

**Issue by Cripix** [pluginsGLPI/order#231]
Bonjour,

Suite a l'installation du plugin "order" je me retrouve dans l’impossibilité d'effectuer une recherche dans la partie "Référence produit" du plugin.

Donc j'ai essayé avec une version qui comporte la derniers des différentes modifications donc je me retrouve avec cette erreur : 
![Annotation 2019-04-15 142635](https://user-images.githubusercontent.com/30194894/56132707-fca04c00-5f8a-11e9-9aff-5f5b21aea8ad.png)

Donc j'attends une solution afin de pourvoir effectuer de nouveau des recherches !

Merci

**Comment by cedric-anne** [comment]
Duplicates #230.
