### ISSUE TITLE
impossible to generate material with 2.5.0 

### ISSUE THREAD

**Issue by orderman** [pluginsGLPI/order#234]
With the plugin 2.5.0 when i want to generate some computer
i have this error 

2019/04/29 09:15:38 [error] 12174#12174: *9293 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /var/www/glpi/plugins/order/inc/reference.class.php:421
Stack trace:
#0 /var/www/glpi/plugins/order/inc/link.class.php(1134): PluginOrderReference->checkIfTemplateExistsInEntity('34', NULL, '5')
#1 /var/www/glpi/plugins/order/inc/link.class.php(574): PluginOrderLink->generateNewItem(Array)
#2 /var/www/g" while reading upstream, client: xx.xxx.xx.x, server: glpipp.mipih.fr, request: "POST /glpi/front/massiveaction.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "sv-t-vtl-glpipp.mipih.net", referrer: "https://sv-t-vtl-glpipp.mipih.net/glpi/plugins/order/front/order.form.php?id=13"
2019/04/29 09:15:38 [error] 12174#12174: *9293 FastCGI sent in stderr: "lpi/inc/massiveaction.class.php(991): PluginOrderLink::processMassiveActionsForOneItemtype(Object(MassiveAction), Object(PluginOrderLink), Array)
#3 /var/www/glpi/inc/massiveaction.class.php(970): MassiveAction->processForSeveralItemtypes()
#4 /var/www/glpi/front/massiveaction.php(59): MassiveAction->process()
#5 {main}
  thrown in /var/www/glpi/plugins/order/inc/reference.class.php on line 421" while reading upstream, client: xx.xxx.xx.x, server: glpipp.mipih.fr, request: "POST /glpi/front/massiveaction.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "sv-t-vtl-glpipp.mipih.net", referrer: "https://sv-t-vtl-glpipp.mipih.net/glpi/plugins/order/front/order.form.php?id=13"

Please Help  
I have to generate the computers manually and link this material to the order one by one
the direct generation does not work

Thanks for your reply

**Comment by orderman** [comment]
I tested with removal of the 2.5.0 plugin and putting back 2.4.0 on my test platform
version 2.4.0 works very well
the trouble comes from the new version 2.5.0
Is there a possible fix?

Thanks

**Comment by orderman** [comment]
I confirm after reinstalling version 2.5 on my test platform the malfunction appears again

**Comment by benjaminEORIS** [comment]
I think, the fix #229 is  not working. 

The value of variable  $add_item['itemtype'] is null.

When I generate item  there is an error **Class name must be a valid object or a string** and the dump of variable is null.

I remove the following lines added by the fix #229  : 

---
         $add_item = $values;

         //retrieve plugin_order_references_id from param if needed
         if (!isset($add_item["plugin_order_references_id"])) {
            $add_item["plugin_order_references_id"] = $params['plugin_order_references_id'];
         }
---
and revert to old version v2.4.0.

---
$add_item = $params['add_items'][$values['id']];

Generate item is working.

**Comment by orderman** [comment]
Hello,

The problem is that this update 2.5.0 is also installed on my production server and I can not go back
on the other hand I am not a specialist in PHP

Is there a fix in preview because I can not create any more
order in good conditions

Thank you for your answers and your work

**Comment by orderman** [comment]
I applied the modification proposed by benjaminEORIS on the version in 2.5.0. Hardware generation works
All plugin features seem to work properly
Thank you

**Comment by xvaldisx** [comment]
I've got the same problem. as i see, i have already got fixed file link.class.php 
But when item is delivered, I couldn't generate any new item or computer. After pressing button "post" I am stuck at page glpi/front/massiveaction.php
after refreshing the page I see the mistake "The action you have requested is not allowed."
