### ISSUE TITLE
empty username or password after install pluging

### ISSUE THREAD

**Issue by luisedazac** [pluginsGLPI/order#238]
sorry for my English
I have installed the version glpi 9.4.2 in shared hosting by cpanel
download version 2.5.0 of order try to install but I got an error Run composer install --no-dev in the plugin directory
I decided to download version 2.4.0 and it was installed well and then I left the application and tried to enter and now I get the following error Username or password empty Log in again
What I can do

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
