### ISSUE TITLE
Additional order templates not available

### ISSUE THREAD

**Issue by it-cairnmillar** [pluginsGLPI/order#246]
GLPI 9.4.2, Orders 2.5.1.
Create a new template and upload to the ~/glpi/plugins/orders/template directory. Template never becomes available from the order template dropdown in the order generation screen.
<img width="444" alt="Screen Shot 2019-07-16 at 9 32 51 am" src="https://user-images.githubusercontent.com/52939851/61255647-beded980-a7ac-11e9-922a-be31c537108d.png">
<img width="362" alt="Screen Shot 2019-07-16 at 9 33 10 am" src="https://user-images.githubusercontent.com/52939851/61255652-c56d5100-a7ac-11e9-9b5d-b7b32854722c.png">

**Comment by it-cairnmillar** [comment]
So, this has been sitting here since July 2019. I take it that there is no interest in this?

**Comment by cedric-anne** [comment]
Hi,

Try to put your template into `/var/www/glpi//files/_plugins/order/templates/`.

Regards
