### ISSUE TITLE
composer install does not work

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/order#250]
Hello

I tried to start composer to install the plugin order but it does not work, could you help me please
Thank you

![image](https://user-images.githubusercontent.com/30655170/70909967-f6c5a380-200e-11ea-9f85-6fb17d31bb54.png)

**Comment by cedric-anne** [comment]
Hi,

Composer is a tier utility. Please refer to https://getcomposer.org/ for its usage.

Regards
