### ISSUE TITLE
Unable to receipt first item

### ISSUE THREAD

**Issue by Maj-72** [pluginsGLPI/order#263]
Hello,
In materiel receipt, when i select all materials, Action, Receipt Materials, i put informations but when validating, the first item is never recepted and an error is shown "operation failed". See below.
Tested on 2 differents GLPI servers. I don't understand the reason.
![image](https://user-images.githubusercontent.com/70270044/91302173-58492f00-e7a6-11ea-9596-f6074d9a7b30.png)

**Comment by elduke78** [comment]
Hello, 

Happens to you only with the first item?


it may be that the profile does not have permission to create an item. When it is received, the item is registered.

Sorry, I don't speak English, I use a translator.

**Comment by TheRoby** [comment]
Hello,
Same error here ... but only on my first command, i tried to reproduce the problem, but I no longer have it ....

Hope it help

**Comment by carlosribeiro** [comment]
I have the same problem. when I have only one item I can't check in.

**Comment by cedric-anne** [comment]
Hi,

Should be fixed by #294 .

Regards
