### ISSUE TITLE
How to change payment condition

### ISSUE THREAD

**Issue by Sandra7fds** [pluginsGLPI/order#275]
Hi ! 
In GLPI plugin order v2.7.0 I'm not allowed to change or add payment condition. Can someone help me to do this. I'm "Super Admin" so I don't think that it's an issue about administration rights. Thanks.

**Comment by nowakt2020** [comment]
Hello, 

Same here. Not possible to add any new payment terms. No predefined either. The '+' sign is grey.

Thanks

**Comment by cedric-anne** [comment]
Duplicates #273
