### ISSUE TITLE
Translation incomplete

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [pluginsGLPI/order#279]
The Translation to Germen is at the Settings-page of the Plugin imcomplete:
![grafik](https://user-images.githubusercontent.com/25504254/130812819-345439a6-0031-4636-b256-bec03f336c62.png)
.
.
.
.
.
.
.
.
.
The Translation of this Strings is a bit wired. In addition it is not exactly clear why it is necessary to add this fields
![grafik](https://user-images.githubusercontent.com/25504254/130812980-19ff4a5e-64b6-4fa0-9625-1588cc55cc9f.png)

**Comment by btry** [comment]
Hi

You can improve translations of the plugin if you have an account on transifex.com. translations are mostly done by the community. 

Translations are usually updated when a new release is published.

**Comment by vollkommenIrrelevant** [comment]
very cool, thank you for invitition.
