### ISSUE TITLE
Bug : Liaison Ticket - Commande n’apparaît pas dans Ticket

### ISSUE THREAD

**Issue by Manu1400** [pluginsGLPI/order#29]
Dans la liste des tickets une massive action "Ajouter un élément" propose d'ajouter au(x) ticket(s) une commande existante.

Or quand je vais dans un des tickets où j'ai associé (dans le passé) une commande, celle-ci n'apparait pas dans l'onglet "Élements".

Le nombre d'éléments (dans le nom de l'onglet) est correct mais cet élément n’apparaît pas alors qu'il est bien dans la base de données (table "glpi_items_tickets", itemtype 'PluginOrderOrder').

**Comment by Manu1400** [comment]
Par contre, le lien apparait correctement dans l'objet Commande : L'onglet "Tickets" indique le bon nombre de Tickets liés et le(s) ticket(s) lié(s) apparaisse(nt) correctement.

**Comment by wawax** [comment]
please submit a pull request to fix the bug

**Comment by wawax** [comment]
this is not a bug, but a misconfiguration.
you need to add Order to to the list of itemtypes available for tickets. This can be done in the 'Assistance' tab of the profile.
