### ISSUE TITLE
Product Reference - There is no link to edit it.

### ISSUE THREAD

**Issue by cadamuroa** [pluginsGLPI/order#291]
Good morning Team,

We are using the order plugin and in the product reference and there is no link to edit the reference that I was created.
Can someone help me?

![image](https://user-images.githubusercontent.com/48462877/141490060-1f00d78e-0950-42e5-b451-ecbe50a953c9.png)

**Comment by tsmr** [comment]
It's due to plugin_order_addSelect function into hook.php

If you comment it it's ok

**Comment by cedric-anne** [comment]
Hi @cadamuroa ,

Could you check #299  ?

Regards
