### ISSUE TITLE
Unable to add assets to an order

### ISSUE THREAD

**Issue by nicolasjo** [pluginsGLPI/order#30]
Hello,

From a 0.85 GLPI version, I was not able to add assets to an order, it's empty. I upgraded my glpi version to 0.90.1 and the assets tabs is empty.

Best regards,

Nicolas

**Comment by proprux** [comment]
Bonjour,

J'ai un probleme similaire. Il m'est impossible d'attribué un ticket à une commande.

Savez-vous pourquoi ?

Cordialement.

--
proprux

**Comment by nicolasjo** [comment]
Aucune idée, c'est dommage car je mise beaucoup sur ce plugin

**Comment by proprux** [comment]
oui egalement pour moi

**Comment by dethegeek** [comment]
Hi
I checked, it appears to be working. 

First, check in your profiles, tab Assistance : the itemtype order must be assosiable to a ticket. 

A second setting allows or prevent orders to be associable to a ticket, individually. Open a ticket, and check the setting "associable to a ticket".

This should solve your issue. 

Thank you for your feed back.

**Comment by Phorms** [comment]
Thank you for this answer - I had the same problem today and I could solve it now.

**Comment by nicolasjo** [comment]
After some digging I found how to proceed, Indeed the targeted audience for the order was not my user, so I wasn't able to add items to my order.

Now it's solved.

Many thanks for your help
