### ISSUE TITLE
Free references bug

### ISSUE THREAD

**Issue by nldrsm** [pluginsGLPI/order#300]
Hello,

I have an issue with free references, when i select  " Add the reference " and i choose the type, i am automaticaly redirect on the home page.

debug mode show this message : 
`PHP Notice (8): Undefined index: name in /var/www/html/glpi10/marketplace/order/inc/order_item.class.php at line 492`
and
`PHP Notice (8): Undefined index: reference_code in /var/www/html/glpi10/marketplace/order/inc/order_item.class.php at line 589`
![image](https://user-images.githubusercontent.com/73691676/152144511-1f175579-3c2e-4ce7-b09e-ed517d0977fb.png)

With GLPI 9.5 and GLPI 10
Thanks for your help

**Comment by jcervantes-sipecom** [comment]
Same here, with GLPI 9.5.7 and plugin 2.7.5 downloaded from marketplace:

When selected "Add the Reference", and Element Type another that the default, per example Devices, the page reload, but cannot add the Reference.

![image](https://user-images.githubusercontent.com/56606032/153664429-0a0bc4ab-d2cc-4f7b-b47a-09668f92bc20.png)

**Comment by cedric-anne** [comment]
Hi,

Fix has been published in version 2.7.6 (for GLPI 9.5) and 2.8.0-r3 (for GLPI 10.0).

Regards
