### ISSUE TITLE
The template cannot be used

### ISSUE THREAD

**Issue by r0bertk** [pluginsGLPI/order#323]
The template cannot be used. After saving an error appears:
Uncaught Exception Error: Call to undefined method PluginOrderOrder :: clone () in /var/www/glpi/src/CommonDBTM.php at line 1224

php-errorr.log:
[2022-06-03 10:34:02] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method PluginOrderOrder::clone() in /var/www/glpi/src/CommonDBTM.php at line 1224
  Backtrace :
  marketplace/order/front/order.form.php:52          CommonDBTM->add()

**Comment by r0bertk** [comment]
Hello, following this solution: https://github.com/glpi-project/glpi/pull/11264/files
the problem is probably fixed.
I added at the beginning:
use Glpi\Features\Clonable;

next add to class: class PluginOrderOrder extends CommonDBTM {
use Clonable;

and finally added:
 public function getCloneRelations(): array
    {
        return [];
    }
}

 Regards

**Comment by cconard96** [comment]
Hello @r0bertk,
Could you open a pull request with this change so it can be fixed in a future release?

**Comment by r0bertk** [comment]
Sorry but i don't know how to make pull request this issues
