### ISSUE TITLE
Erreur à l'ainstallation

### ISSUE THREAD

**Issue by kabdriver** [pluginsGLPI/order#34]
L'erreur à l'installation se produit 
`update itemtype of table glpi_tickets for PluginOrderBudget - Erreur durant l'Ã©xecution de la requÃªte : UPDATE`glpi_tickets`SET`itemtype`= 'PluginOrderBudget' WHERE`itemtype`= '3153' - L'erreur est Unknown column 'itemtype' in 'where clause'`

**Comment by wawax** [comment]
Hello,

What is the GLPi & plugin version ?
From which plugin version are you upgrading ?

**Comment by wawax** [comment]
Please provide informations otherwise I would close this ticket.

Thank you.

**Comment by trasher** [comment]
Closing as no feedback.
