### ISSUE TITLE
Error when try to delete something in the GLPI 10.0.7

### ISSUE THREAD

**Issue by cadamuroa** [pluginsGLPI/order#357]
Hi Team, 

Can someone help me?
When I try to delete something in the GLPI server I get this error message:

![image](https://github.com/pluginsGLPI/order/assets/48462877/1aa7e8d5-2c28-4e73-a8f5-3f53d448ae2c)

This error is from Order Plugin? Someone get this error before?

[2023-05-17 18:01:51] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid relations declared between "glpi_plugin_order_othertypes" and "glpi_plugin_order_others" table. Target field "othertypes_id" is not a foreign key field. in ..\glpi\src\DbUtils.php at line 2144
  Backtrace :
  src\DbUtils.php:2144                               trigger_error()
  inc\db.function.php:585                            DbUtils->getDbRelations()
  src\CommonDBTM.php:866                             getDbRelations()
  src\CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
  src\CommonDBTM.php:2064                            CommonDBTM->deleteFromDB()
  src\MassiveAction.php:1495                         CommonDBTM->delete()
  src\MassiveAction.php:1408                         MassiveAction::processMassiveActionsForOneItemtype()
  src\MassiveAction.php:1386                         MassiveAction->processForSeveralItemtypes()
  front\massiveaction.php:59                         MassiveAction->process()
  public\index.php:73                                require()

**Comment by cedric-anne** [comment]
Fixed in 2.10.4.
