### ISSUE TITLE
Error 500 - duplicate keys found

### ISSUE THREAD

**Issue by Aekinox** [pluginsGLPI/order#369]
Hi,
glpi: 10.0.11
plugin: 2.10.4
we have an error 500 when we try to go to the orders section:
_PHP Warning:  Duplicate keys found in search options for item type PluginOrderOrder: 30 in D:\Inetpub\dev-glpi\src\Search.php on line 8288_

**Comment by IP-V15** [comment]
I have the same problem with glpi 10.0.12 and the last version of plugin : 
_Warning
: Duplicate keys found in search options for item type PluginOrderOrder: 30 in
C:\xampp\htdocs\glpi\src\Search.php
on line
8284_

**Comment by Aekinox** [comment]
Hi
it works for me, no more error !!!

**Comment by stonebuzz** [comment]
Fixed by https://github.com/pluginsGLPI/order/commit/7adef7ec95345c9a026b3eb907ac718fe90e674b

**Comment by IP-V15** [comment]
it works for me too
thanks !
