### ISSUE TITLE
Unable to add item to an order 

### ISSUE THREAD

**Issue by informaticaCMC** [pluginsGLPI/order#42]
I cannot add items to an order, there is a Drop Down under Type but its Blank (----- ) , I created many diferences Products references and other items type but when I try to add one to a orde the drop down box does not show anything.

I'm working with GLPI 0.9.1 and order management pluging 0.85+1.2

**Comment by wawax** [comment]
Hello,

Do you have a supplier for the order ? They are references associated to this supplier ?

**Comment by informaticaCMC** [comment]
Hello Wawax, yes we have a supplier for the orden, and we have reference supplier too. But they are different. Should be the same?

**Comment by CarlSW** [comment]
Hello,

I am having the same issue.  I have setup the Supplier, Budget, Payment conditions and everything else.  When I come to add a Order Item,  it just says that it is loading.

![image](https://cloud.githubusercontent.com/assets/22521905/18954207/cb4f4060-8649-11e6-98fd-30e103f1b7f8.png)

![image](https://cloud.githubusercontent.com/assets/22521905/18954252/008362c0-864a-11e6-992d-c2a7abc36f35.png)

I am using GLPI 0.90.5 and Order Maintenance 0.85+1.3.1

Thanks in advance.

**Comment by trasher** [comment]
I'm not able to reproduce.

Please switch to debug mode and report any error;
Please also check glpi/files/sql-errors & php-errors logfiles.

Thank you.

**Comment by cedric-anne** [comment]
Hi,

This works fine in last versions of GLPI an Order plugin.

Regards
