### ISSUE TITLE
Add Fields Location, group and status in the generation equipment.

### ISSUE THREAD

**Issue by amma35** [pluginsGLPI/order#44]
Goal : 
Add Fields Location, group and status in the generation equipment.

I send a pull request as soon as possible.

**Comment by wawax** [comment]
Hello,

But it is not already the case ? For the location, I'm sure it is. Which group and status do you want to set ?

**Comment by amma35** [comment]
Yes from config you can add location of object from the order location but you can specify her from generation form like this ?

![generation](https://cloud.githubusercontent.com/assets/15138371/14206832/30e74070-f816-11e5-91db-206d3f52c628.png)

**Comment by wawax** [comment]
Be careful, there's an option to affect the order's location to the generated item.
If the option is active, the location dropdown should not (I think) be displayed

**Comment by amma35** [comment]
Ok I check

**Comment by wawax** [comment]
Replaced by https://github.com/pluginsGLPI/order/pull/49
