### ISSUE TITLE
Impossible d'ajouter  des éléments à ma commande

### ISSUE THREAD

**Issue by Servinfo** [pluginsGLPI/order#52]
GLPI v 0.90.4 
Plugins Order 0.85 +1.2
Fournisseur ok
Référence Produit ok
Liaison Référence Produit et fournisseur ok
Budget ok
Création de l'en tête de commande ok
Le passage au détail de la commande (éléments de la commande) s'effectue bien mais hormis le message de chargement il ne se passe plus rien.
![gpli_order1](https://cloud.githubusercontent.com/assets/20796141/17331499/83bb99b6-58cb-11e6-9776-866b6f47c386.jpg)
![gpli_order2](https://cloud.githubusercontent.com/assets/20796141/17331500/83dd1938-58cb-11e6-9b43-6082cd06debb.jpg)

**Comment by wawax** [comment]
Please switch to debug mode and report any error;
Please also check glpi/files/sql-errors & php-errors logfiles.

Thank you.

**Comment by trasher** [comment]
duplicates #42
