### ISSUE TITLE
problem of migration, order:  1.6.0 -> 0.85+1.1  and  glpi: 0.83.4 -> 0.90.5

### ISSUE THREAD

**Issue by Quantique372** [pluginsGLPI/order#54]
Hello,

Since the migration, I no longer displays the notes in order.

After checking on the database in "glpi_plugin_order_orders" then "notepad", well I find my data, but nothing to display the web page.

Would you have a solution?

**Comment by trasher** [comment]
See ini GLPi logs (php and sql logs) if something is displayed.

**Comment by trasher** [comment]
ping?

**Comment by cedric-anne** [comment]
Hi,

Without any logs, we cannot investigate. I close this issue.

Regards
