### ISSUE TITLE
No translation some words

### ISSUE THREAD

**Issue by AircraftRu** [pluginsGLPI/order#58]
In settings:
![glpi - order - google chrome 2016-09-15 11 12 48](https://cloud.githubusercontent.com/assets/17082164/18543203/49553b4a-7b37-11e6-8cb1-10164c268c5f.png)

On Transifex Ru 100% translate.

**Comment by trasher** [comment]
Strings was not extracted... Should be OK now, I've updated the POT file on transifex.
