### ISSUE TITLE
Page blanche à l'ajout d'une facture

### ISSUE THREAD

**Issue by stonebuzz** [pluginsGLPI/order#61]
En fonction du type d'affichage Glpi,
l'ajout d'une facture n'est pas possible .

Si l'affichage est de type "Onglet sur la gauche"  l'affichage est correcte.
Pour les autres , nous arrivons sur une page blanche (sans erreur PHP ou Apache).

Cordialement

**Comment by trasher** [comment]
Bonjour,

Une page blanche sans erreur, c'est plutôt étonnant... Sur les erreurs fatales de ce type, l'erreur est généralement loguée dans le log apache (si `mod_php` est utilisé) ou dans le log de fpm (si c'est fpm qui est utilisé).

**Comment by stonebuzz** [comment]
Après vérification il n'y à rien dans les logs apache2, php, glpi.
Idem en mode debug sur Glpi

**Comment by flegastelois** [comment]
Je confirme, il manque certainement une méthode PluginOrderBill::addDefaultFormTab

**Comment by trasher** [comment]
@flegastelois en toute honnêteté ; je ne sais pas. Mais c'est en dehors du pérmiètre de ce ticket, si tu penses qu'il faut changer, peux-tu ouvrir un autre ticket ? Merci :)
