### ISSUE TITLE
GLPI 0.90.5 & OM 0.85+1.3.1 / Command with many items

### ISSUE THREAD

**Issue by dr-redoute** [pluginsGLPI/order#69]
**Current setup**
- GLPI 0.95.0
- Order Management 0.85+1.3.1
- Data Injection 2.4.2
- OCS Inventory NG 1.2.1

**Issue**

We need to create a purchase order with many items (5 or 6 different references with qty > 100) and it seems we are hitting a limit (same problem described [here](http://forum.glpi-project.org/viewtopic.php?id=153144)). We found no way around this problem (raising PHP memory limit, raising max number of displayed items in searches/dropdown lists or modifying Order Management plugin parameters).

We get the following message displayed if we try to delete/add/receive any items already added to the order:

_The action you have requested is not allowed. / L'action que vous avez réalisée n'est pas autorisée._

Debug level is set at 5.

No errors in sql-errors.log

The only message we have is in php-errors.log around the time we tried to alter the command:

```
 From PluginOrderOrder::isOverBudget() in /usr/share/glpi/plugins/order/inc/order.class.php line 1829
  Budget Object
  (
      [dohistory] => 1
      [usenotepad:protected] => 1
      [can_be_translated] =>
      [must_be_replace] =>
      [first_level_menu] => config
      [second_level_menu] => CommonDropdown
      [third_level_menu] =>
      [display_dropdowntitle] => 1
      [fields] => Array
          (
              [id] => 3
              [name] => 5914B
              [entities_id] => 0
              [is_recursive] => 0
              [comment] => Rénovation Poste de travail
              [is_deleted] => 0
              [begin_date] =>
              [end_date] =>
              [value] => 0.0000
              [is_template] => 0
              [template_name] =>
              [date_mod] => 2016-09-29 16:47:18
          )

      [history_blacklist] => Array
          (
          )

      [auto_message_on_action] => 1
      [no_form_page] =>
      [additional_fields_for_dictionnary] => Array
          (
          )

      [fkfield:protected] =>
      [searchopt:protected] =>
      [taborientation] => vertical
      [get_item_to_display_tab] => 1
      [mailqueueonaction] =>
      [type:protected] => -1
      [displaylist:protected] => 1
      [showdebug] =>
  )

```

**Comment by wawax** [comment]
Hello,

Could you copy/paste data between [code] and [/code] in Setup > General > System ?

Thank you.

**Comment by dr-redoute** [comment]
GLPI 0.90.5 (/glpi => /usr/share/glpi)

Server
 
Operating system: Linux XXX.YYY.ZZZ 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64
PHP 5.4.45 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl,
	date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, igbinary, imap, intl, json, ldap, libxml, lzf,
	mbstring, mcrypt, mhash, msgpack, mysql, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sockets,
	sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) PHP/5.4.45 mod_perl/2.0.9dev Perl/v5.16.3 ()
	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Server Software: MariaDB Server
	Server Version: 5.5.50-MariaDB
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
OK/etc/glpi : OK
OK/var/lib/glpi/files : OK
OK/var/lib/glpi/files/_dumps : OK
OK/var/lib/glpi/files/_sessions : OK
OK/var/lib/glpi/files/_cron : OK
OK/var/lib/glpi/files/_graphs : OK
OK/var/lib/glpi/files/_lock : OK
OK/var/lib/glpi/files/_plugins : OK
OK/var/lib/glpi/files/_tmp : OK
OK/var/lib/glpi/files/_rss : OK
OK/var/lib/glpi/files/_uploads : OK
OK/var/lib/glpi/files/_pictures : OK
OK/var/log/glpi : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
OKSELinux mode is Enforcing
OKSELinux boolean configuration for httpd_can_network_connect --> on
OKSELinux boolean configuration for httpd_can_network_connect_db --> on
OKSELinux boolean configuration for httpd_can_sendmail --> on

Libraries
 
htmLawed version 1.1.22 in (/usr/share/php/htmLawed)
phpCas version 1.3.4 in (/usr/share/pear)
PHPMailer version 5.2.14 in (/usr/share/php/PHPMailer)
ZetaComponent ezcGraph installed in (/usr/share/php/ezc):  OK
Zend Framework in (/usr/share/php/Zend)
SimplePie version 1.3.1 in (/usr/share/php/php-simplepie)
TCPDF version 6.2.12 in (/usr/share/php/tcpdf)
ircmaxell/password-compat in (/usr/share/php/password_compat). Compatitility: Ok

LDAP directories
 
Server: 'xxx.yyy.zzz', Port: '389', BaseDN: 'dc=yyy,dc=zzz', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'cn=svcglpi,ou=Applis,ou=Accounts,dc=yyy,dc=zzz', Use TLS: none
Server: 'aaa.bbb.ccc', Port: '389', BaseDN: 'dc=bbb,dc=ccc', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'cn=svcglpi,ou=Applis,ou=Accounts,dc=bbb,dc=ccc', Use TLS: none

Mysql replicas
 
Not active

Notifications
 
Way of sending emails: PHP

Mails receivers
 

Plugins list
 
	simcard              Name: Gestion de cartes SIM          Version: 1.4.2      State: Enabled
	order                Name: Gestion des commandes          Version: 0.85+1.3.1 State: Enabled
	datainjection        Name: Injection de fichiers          Version: 2.4.2      State: Enabled
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.2.1      State: Enabled
	webservices          Name: Web Services                   Version: 1.6.0      State: Enabled

OCS Inventory NG
Host: localhost
Connection: Ok
Use the OCSNG software dictionary: No

**Comment by dr-redoute** [comment]
Important Update!

Someone from TecLib helped me yesterday to setup a new test server using 9.1 version and same plugins. Same error. He altered /etc/php.ini adding `max_input_vars = 2000` and the problem was gone: I was able to create/modify orders with order lines for high qty of products.

I applied same change to /etc/php.ini of my 0.90.5 test server and problem is gone.

It seems he spent quite some time (1-2 hours) searching for clues (no error messages in any log files).

He still has to check & decide wether the change to php.ini is a mere workaround for something that needs to be changed in GLPI or plugin code.

Ask PLebel for name of TecLib guy who did the troubleshooting if you need more info.
