### ISSUE TITLE
Associer Ticket à commande

### ISSUE THREAD

**Issue by Manondescodessources** [pluginsGLPI/order#74]
Bonjour,

Je ne trouve pas comment associer un ticket à une commande. Ce serait pourtant bien pratique pour avoir le suivi du matériel commandé suite à ce ticket.

Merci par avance !

**Comment by davidrmasson** [comment]
Bonjour, 

Je rencontre exactement le même soucis. Avez-vous du nouveau de votre coté ?

**Comment by Manondescodessources** [comment]
Bonjour,

Désolé pour le temps de réponse, je n'ai pas eu le temps de me repencher sur le sujet. Mais malheureusement, je n'ai pas de pistes.

**Comment by Guanymede** [comment]
Bonjour,

Prérequis :  dans le profil qui utilisera "commandes", il faut aller dans l'onglet "Assistance" puis dans la rubrique "association" dans "matériel associable à un ticket" ajouter "commande".
Ce n'est pas très intuitif... mais sinon, impossible de pouvoir lier tickets et commandes...

2 façons de procéder pour lier les 2 objets : 

A) Le ticket de demande de commande a déjà été créé (=demande de commande)
1 - Lors de la création de la commande, il faut bien indiquer le champ "associable à un ticket" = Oui
2 - Ensuite on retourne sur le ticket que l'on souhaite associer à la commande et dans son onglet " éléments" on peut maintenant choisir un type commande puis associer la commande souhaitée.

B) Un ticket sera créé suite à la création de la commande
1- Créer la commande en renseignant bien tous les champs
2- aller dans l'onglet "ticket" de la commande et cliquer sur "Nouveau Ticket pour cet élément"

**Comment by Manondescodessources** [comment]
C'est super ! C'est donc résolu, merci beaucoup pour ce retour.

**Comment by alexgrd01** [comment]
> 
> 
> Bonjour,
> 
> Prérequis : dans le profil qui utilisera "commandes", il faut aller dans l'onglet "Assistance" puis dans la rubrique "association" dans "matériel associable à un ticket" ajouter "commande".
> Ce n'est pas très intuitif... mais sinon, impossible de pouvoir lier tickets et commandes...
> 
> 2 façons de procéder pour lier les 2 objets :
> 
> A) Le ticket de demande de commande a déjà été créé (=demande de commande)
> 1 - Lors de la création de la commande, il faut bien indiquer le champ "associable à un ticket" = Oui
> 2 - Ensuite on retourne sur le ticket que l'on souhaite associer à la commande et dans son onglet " éléments" on peut maintenant choisir un type commande puis associer la commande souhaitée.
> 
> B) Un ticket sera créé suite à la création de la commande
> 1- Créer la commande en renseignant bien tous les champs
> 2- aller dans l'onglet "ticket" de la commande et cliquer sur "Nouveau Ticket pour cet élément"

Bonjour, je n'arrive toujour pas à lier une commande à mon ticket, avez vous d'autres informations? je suis en version 9.4.2 de GLPI et 2.5.2 du plugin order. Merci d'avance

**Comment by kenza-benazzou** [comment]
Bonjour 
Je n'arrive pas à lier la commande à un ticket même-ci j'ai choisi associable à un ticket, j'utilise GLPI version 10.0.3 et version 2.10.0 du plugin order.
Merci d'avance
