### ISSUE TITLE
Create table from Order.php

### ISSUE THREAD

**Issue by Yadep** [pluginsGLPI/order#75]
Hello, 
I need change the construction of the table in plugins/order/front/order.php,
But i didn't find the SQL query, i've search on the code and on the internet but i found nothing if someone can tell me where are the query for the table who show all order ?

Thanks.

/////////////////////

Bonjour, 
j'ai besoin de modifier la construction du tableau du plugin order,
en effet je cherche a modifier la requête SQL du tableau dans plugins/order/front/order.php qui permet d'afficher toutes les commandes mais même en ayant fait le tour du code je ne trouve pas la construction du tableau.
Mon plugin order est en 0.85+1.0 et mon glpi en 0.85.5.
Si quelqu'un sait ou trouver sa.
Merci d'avance

**Comment by trasher** [comment]
There is no method in the plugin to generate the list; ll is based on core features; you can override some parts, but this is development; consider reading the development docs.
