### ISSUE TITLE
Note de qualité fournisseur sur 10 au lieu de sur 5

### ISSUE THREAD

**Issue by johannsan** [pluginsGLPI/order#76]
Bonjour.

Lorsqu'on note un fournisseur, la note est sur 5 car il y a 5 étoiles.
La note est alors enregistrée sur 5 (ce qui est normal) dans glpi_plugin_order_surveysuppliers.

Par contre, sur la page : 
/plugins/order/front/order.form.php?id=6
La note résultante est 3/10 lorsqu'on a sélectionné 1,2,3,4,5 au lieu de 3/5 ou 6/10

Idem sur la fiche fournisseur : 
/plugins/order/front/surveysupplier.form.php?id=5&plugin_order_orders_id=6
Fournisseur:    Fournisseur test
Qualité du suivi administratif (contrat, factures, courrier...):   1 etoile
Qualité du suivi commercial, fréquence des visites, réactivité: 2 etoiles
Disponibilité des interlocuteurs fournisseur:   3 etoiles
Qualité des prestations collaborateurs du fournisseur:  4 etoiles
Fiabilité sur les disponibilités annoncées:  5 etoiles
Commentaires:  
Note moyenne sur 10 (X points / 5):  3.00 / 10 ==> Normalement ca devrait etre 6/10 ou 3/5

Cdt

**Comment by johannsan** [comment]
A noter que le fichier:surveysupplier.class.php que j'ai contient : "/5" et non sur "/5*2" comme indiqué à l'adresse suivante : https://github.com/pluginsGLPI/order/pull/33/files


 public function getTotalNotation($plugin_order_orders_id) {
      global $DB;

      $table = $this->getTable();
      $query  = "SELECT (`answer1` + `answer2` + `answer3` + `answer4` + `answer5`) AS total
                 FROM `$table`
                 WHERE `plugin_order_orders_id` = '$plugin_order_orders_id'";
      $result = $DB->query($query);
      if ($DB->numrows($result)) {
         return $DB->result($result, 0, "total") /5;
      } else {
         return 0;
      }
   }

**Comment by trasher** [comment]
For reference, what seems to be the original specification for that (only available in french):

> Concept : Ajouter un sondage par commande pour les fournisseurs
>
> 5 Notations (de 1 à 10)
> 
>     Qualité du suivi administratif (contrat, factures, courrier, )
>     Qualité du suivi commercial, fréquence des visites, réactivité
>     Disponibilité des interlocuteurs fournisseur
>     Qualité des prestations collaborateurs du fournisseur
>     Fiabilité sur les disponibilités annoncées
> 
> Note moyenne sur 10 (10 notations : X points / 5)
> 
> + un commentaire
> 
> Sur la fiche du fournisseur :
> Note globale et liens vers les commandes avec le commentaire associé.

**Comment by trasher** [comment]
Fixed in 3dcfe93384a114d305d8cb2240eb90e622adae31
