### ISSUE TITLE
Gestion des commandes: erreur de caractère sur bon de commande

### ISSUE THREAD

**Issue by samakehamed** [pluginsGLPI/order#82]
Bonjour à tous,
Je suis un nouvel utilisateur de glpi.
J'ai installé et activé le plugin Gestion des commandes. Tout se passe bien, sauf que lorsque je génère le bon de commande,
j'obtiens des erreurs de caractères dans les champs contenant un nombre>=1000.
J'ai l'impression que cela est lié au séparateur de milliers.
Par exemple, au lieu de **5 204,70** j'ai **5Â 204,70** sur le bon de commande
Quelqu'un pourrait-il m'aider à résoudre ce problème?
Merci par avance

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce the problem using last version of GLPI + plugin.
Could you upgrade to a most recent version of the plugin and check if you still have the problem ?

Regards

**Comment by cedric-anne** [comment]
Hi,

Without feedback, I cannot investigate. I close this issue. Feel free to reopen.

Regards
