### ISSUE TITLE
Génération du bon de commande impossible

### ISSUE THREAD

**Issue by Manondescodessources** [pluginsGLPI/order#83]
Bonjour,

Lorsque je clique sur "Génération du document", j'ai une erreur me disant que la page ne fonctionne pas, comme si elle était inexistante.

Merci pour votre réponse !

Manon

**Comment by Manondescodessources** [comment]
Des pistes que je recherche :

Je me demande si ce ne serait pas un problème de librairie manquante sur mon serveur. Quoi qu'à priori, le dossier odtphp existe dans le dossier lib du plugin.

Ce serait bien d'avoir un petit retour sur ce bug.

Parvenez-vous à générer un document ou non ? Merci pour vos réponses ...

**Comment by trasher** [comment]
Hi,

Do you have any error in glpi logs files (`files/_log/php-errors.log` and `files/_log/sql-errors.log`)? If something is missing or going wrong, you'll see it in the logs.

**Comment by trasher** [comment]
ping?

**Comment by Manondescodessources** [comment]
Hello, 

Here my php-errors.log file 

`2017-03-06 08:47:15 [2@GLPI]
  *** PHP Warning(2): mkdir(): Permission denied
  Backtrace :
  :                                                  
  plugins/order/lib/Odtphp/Zip/PclZipProxy.php:51    mkdir()
  plugins/order/lib/Odtphp/Odf.php:65                Odtphp\Zip\PclZipProxy->open()
  plugins/order/inc/order.class.php:1448             Odtphp\Odf->__construct()
  plugins/order/front/export.php:33                  PluginOrderOrder->generateOrder()
2017-03-06 08:47:15 [2@GLPI]
  *** PHP Warning(2): mkdir(): Permission denied
  Backtrace :
  :                                                  
  plugins/order/lib/Odtphp/Zip/PclZipProxy.php:51    mkdir()
  plugins/order/lib/Odtphp/Segment.php:113           Odtphp\Zip\PclZipProxy->open()
  plugins/order/inc/order.class.php:1583             Odtphp\Segment->merge()
  plugins/order/front/export.php:33                  PluginOrderOrder->generateOrder()
2017-03-06 08:47:15 [2@GLPI]
  *** PHP Warning(2): mkdir(): Permission denied
  Backtrace :
  :                                                  
  plugins/order/lib/Odtphp/Zip/PclZipProxy.php:51    mkdir()
  plugins/order/lib/Odtphp/Odf.php:296               Odtphp\Zip\PclZipProxy->open()
  plugins/order/lib/Odtphp/Odf.php:331               Odtphp\Odf->_save()
  plugins/order/inc/order.class.php:1644             Odtphp\Odf->exportAsAttachedFile()
  plugins/order/front/export.php:33                  PluginOrderOrder->generateOrder()
2017-03-06 08:47:15 [2@GLPI]
  *** PHP Warning(2): file_put_contents(./tmp/content.xml): failed to open stream: No such file or directory
  Backtrace :
  :                                                  
  plugins/order/lib/Odtphp/Zip/PclZipProxy.php:96    file_put_contents()
  plugins/order/lib/Odtphp/Odf.php:298               Odtphp\Zip\PclZipProxy->addFromString()
  plugins/order/lib/Odtphp/Odf.php:331               Odtphp\Odf->_save()
  plugins/order/inc/order.class.php:1644             Odtphp\Odf->exportAsAttachedFile()
  plugins/order/front/export.php:33                  PluginOrderOrder->generateOrder()`

**Comment by trasher** [comment]
Hi,

Thanks for the logs. I guess your issue has been solved in the latest plugin release; since we make a few corrections on the ODTPHP lib and the paths that were used to generate data.

Please try with 1.9.6; and let us know if that solve your issue.

**Comment by Manondescodessources** [comment]
Wow ! Very reactiv ! 

I try it now ...

**Comment by Manondescodessources** [comment]
Same error with a different php-errors.log

`2017-03-06 08:59:13 [2@GLPI]
  *** PHP Warning(2): include_once(/var/www/html/goulpi/plugins/order/vendor/autoload.php): failed to open stream: No such file or directory
  Backtrace :
  plugins/order/setup.php:65                         
  plugins/order/setup.php:65                         include_once()
  inc/plugin.class.php:141                           include_once()
  inc/includes.php:116                               Plugin::load()
  plugins/order/front/export.php:30                  include()
2017-03-06 08:59:13 [2@GLPI]
  *** PHP Warning(2): include_once(): Failed opening '/var/www/html/goulpi/plugins/order/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear')
  Backtrace :
  plugins/order/setup.php:65                         
  plugins/order/setup.php:65                         include_once()
  inc/plugin.class.php:141                           include_once()
  inc/includes.php:116                               Plugin::load()
  plugins/order/front/export.php:30                  include()
2017-03-06 08:59:20 [@GLPI]
  *** PHP Warning(2): include_once(/var/www/html/goulpi/plugins/order/vendor/autoload.php): failed to open stream: No such file or directory
  Backtrace :
  plugins/order/setup.php:65                         
  plugins/order/setup.php:65                         include_once()
  inc/plugin.class.php:258                           include_once()
  inc/plugin.class.php:115                           Plugin->checkStates()
  inc/includes.php:110                               Plugin->init()
  plugins/fusioninventory/index.php:49               include()
2017-03-06 08:59:20 [@GLPI]
  *** PHP Warning(2): include_once(): Failed opening '/var/www/html/goulpi/plugins/order/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear')
  Backtrace :
  plugins/order/setup.php:65                         
  plugins/order/setup.php:65                         include_once()
  inc/plugin.class.php:258                           include_once()
  inc/plugin.class.php:115                           Plugin->checkStates()
  inc/includes.php:110                               Plugin->init()
  plugins/fusioninventory/index.php:49               include()
`

**Comment by trasher** [comment]
It complains about a missing file ; that is present in the last release. Please pake sure y'ouve downloaded the release, and not the source code.

Also make sur that the old plugin is no longer in your plugins directory (renaming it is not enough; it must be moved elsewhere).

**Comment by Manondescodessources** [comment]
YES !

Downloading the last version is working !

Thanks a lot !

Very good job with this plugin !

**Comment by Manondescodessources** [comment]
Can I mark as solved ?
