### ISSUE TITLE
Enable automatic record doesn't work

### ISSUE THREAD

**Issue by dragosnimu123** [pluginsGLPI/order#88]
Hi,
I have configured the feature to Yes but no functionality.
Immediate record works well
Thanks

**Comment by cedric-anne** [comment]
Hi,

The only feature I found that could be related to your issue is the automatic generation of assets. It works weel for me. Assets are automatically generated when marked as delivered.

If you are talking about something else, could you explain steps to reproduce ?

Regards

**Comment by cedric-anne** [comment]
Hi,

Without feedback, I cannot investigate. I close this issue. Feel free to reopen.

Regards
