### ISSUE TITLE
Translation not enabled

### ISSUE THREAD

**Issue by AlexNikolaenko** [pluginsGLPI/order#92]
After first install of plugins translarion ru_RU not enabling. 

glpi:~$ ls -la /usr/share/glpi/plugins/order/locales/
-rw-rw-r--  1 root root 26667 окт 25 19:16 cs_CZ.po
-rw-rw-r--  1 root root 14167 окт 25 19:16 de_DE.mo
-rw-rw-r--  1 root root 26301 окт 25 19:16 de_DE.po
-rw-rw-r--  1 root root 13622 окт 25 19:16 en_GB.mo
-rw-rw-r--  1 root root 25466 окт 25 19:16 en_GB.po
-rw-rw-r--  1 root root 13571 окт 25 19:16 es_ES.mo
-rw-rw-r--  1 root root 26143 окт 25 19:16 es_ES.po
-rw-rw-r--  1 root root 15107 окт 25 19:16 fr_FR.mo
-rw-rw-r--  1 root root 26957 окт 25 19:16 fr_FR.po
-rw-rw-r--  1 root root 13398 окт 25 19:16 it_IT.mo
-rw-rw-r--  1 root root 25556 окт 25 19:16 it_IT.po
-rw-rw-r--  1 root root 21015 окт 25 19:16 order.pot
-rw-rw-r--  1 root root 25774 окт 25 19:16 pl_PL.po
-rw-rw-r--  1 root root 23188 окт 25 19:16 pt_BR.po
-rw-rw-r--  1 root root 21932 окт 25 19:16 ro_RO.po
-rw-rw-r--  1 root root 30672 окт 25 19:16 ru_RU.po
-rw-rw-r--  1 root root 30672 окт 25 19:16 ru_RU.mo
-rw-rw-r--  1 root root 26398 окт 25 19:16 tr_TR.po

**Comment by trasher** [comment]
Hello,

With latest plugin release, I can see russian translation (many strings are not translated):
![order_ru](https://cloud.githubusercontent.com/assets/224733/22097114/ac3eed28-de1f-11e6-823d-eecaf9763695.png)

Are you using the 1.9.5 release (latest)?

**Comment by AlexNikolaenko** [comment]
ru_RU.po contain complete translation, but somehow it is not used 
=============
#: inc/config.class.php:94
msgid "Default VAT"
msgstr "НДС по умолчанию"

#: inc/config.class.php:106
msgid "Use validation process"
msgstr "Использовать проверку заказов"

#: inc/config.class.php:113
msgid "Order generation in ODT"
msgstr "Выгружать заказ в формат ODT"

#: inc/config.class.php:119
msgid "Activate suppliers quality satisfaction"
msgstr "Включить оценку качества постащиков"
============

**Comment by trasher** [comment]
You're right, I did not check if the translation was done. I can see that the PO file is not up to date (for example, "Default VAT" in on line 89 now, not on 94; but it should not cause such an issue.

I do not understand what is wrong for now, I'll investigate.

**Comment by trasher** [comment]
Seems like there were an issue on the existing po file... That will be fixed in the next release.
